language: node_js
node_js:
  - "14"
dist: trusty
sudo: required
branches:
  only:
  - main
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod --base-href https://mtiwari95.github.io/angular-latest/